baseURL = 'https://aliseyyidoglu.netlify.app/'
languageCode = 'en-US'
theme = 'etch'
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

title = "Ali Osman Seyyidoglu"

[params]
  description = "Technical education content."
  copyright = "This site uses Etch created by Lukas Joswiak. Learn more at https://github.com/LukasJoswiak/etch"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "about"
    url = "/about/"
    weight = 20

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    title = "resume"
    url = "/resume/"
    weight = 30

  [[menu.main]]
    identifier = "resume-en"
    name = "Resume (EN)"
    title = "resume-en"
    url = "/resume-en/"
    weight = 40
    parent = "resume"

  [[menu.main]]
    identifier = "resume-tr"
    name = "Resume (TR)"
    title = "resume-tr"
    url = "/resume-tr/"
    weight = 50
    parent = "resume"

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
