baseURL = 'https://aliseyyidoglu.netlify.app/'
languageCode = 'en-US'
theme = 'etch'
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

title = "Ali Seyyidoglu"

[params]
  description = "Technical education content."
  copyright = "Copyright © 2023 Ali Seyyidoglu | Hugo Theme: Lukas Joswiak"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
